# Generated by Django 3.1.2 on 2020-10-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='user',
        ),
    ]
